### ISSUE TITLE
CI should run Lint, Flow, and Prettier checks for every PR

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#67]
The `package.json` defines a [`check-all`](https://github.com/reactjs/reactjs.org/blob/be1f9a60d80261eb70eded915b266078b606524c/package.json#L71) script that runs Prettier, Lint, and Flow. This script is intended to be run before commit to help catch inconsistent formatting or type errors. However we are not currently running this check as part of CI.

- [x] To fix this, first create a script that does the following (done via #93)
  * Run Prettier and fail if any modifications are made. (This means that the committed code isn't formatted correctly.)
  * Run ESLint and fail if there are any errors.
  * Run Flow and fail if there are any errors.
- [x] Fix all pre-existing errors so the new `yarn ci-check` task passes in `master`. (done via #104)
- [x] Hook this new script into CircleCI to run automatically for every PR. (A React team member will need to help with this step.) (done via #131)

**Comment by jxom** [comment]
@bvaughn - I'd be willing to do this.

**Comment by bvaughn** [comment]
This issue is all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Re-opening b'c only the first part is done 😄

**Comment by jxom** [comment]
Sorry @bvaughn - I already made changes for the second one :P see #104

**Comment by bvaughn** [comment]
Don't be sorry. This issue is still marked "in-progress" so that's great 👍

**Comment by jxom** [comment]
@bvaughn - I guess I'll open a PR to hook the script into CircleCI too! :)

**Comment by bvaughn** [comment]
Thanks @jxom for your help getting this done!
