### ISSUE TITLE
Bugs and issues umbrella

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#84]
We just completely rewrote docs in facebook/react/issues/7864.
They're bound to cause some issues, have some mistakes, etc.
Let's keep this issue as an umbrella for all problems we're discovering after the initial rollout.

## Claimable
- [ ] Mention in default index.html that it is not production-ready
- [ ] Figure out what to do with Community section (https://github.com/facebook/react/pull/6099)

## In-progress
- [x] @annuhdo: Mark `mockComponent` as legacy and unnecessary (react/issues/2499#issuecomment-94044857)
- [x] @ishankbahl: `shallowCompare` on Addons page should recommend `PureComponent` instead

If you'd like to claim any of the above items, leave a comment and we'll update this issue!

Migrated from facebook/react/issues/8035

**Comment by annuhdo** [comment]
Ooh, I'll grab the issue "Mark mockComponent as legacy and unnecessary" assuming it's to change this section: https://reactjs.org/docs/test-utils.html#mockcomponent

**Comment by bvaughn** [comment]
Okay it's yours

**Comment by ishankbahl** [comment]
Made a PR for "`shallowCompare` on Addons page should recommend `PureComponent` instead".

**Comment by ishankbahl** [comment]
@bvaughn the last two issues had been solved, maybe someone forgot to tick them off at https://github.com/facebook/react/issues/8035 .

**Comment by bvaughn** [comment]
Yup! You're right! String refs are mentioned [here](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs) and it looks like all of the forms examples show controlled components now. Thanks for pointing this out! Description has been updated.

**Comment by shawninder** [comment]
I added an issue about the docs in the wrong place so it was closed. Hopefully this is the right place: https://github.com/facebook/react/issues/11221
